# Producao (Render)
app.cors.allowed-origins=https://tcc-workspace.vercel.app

# JPA em producao (mantido conforme decisao)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
